### ISSUE TITLE
Cannot use ctx.voice_channel 

### ISSUE THREAD

**Issue by Karnatour** [HazemMeqdad/lavaplay.py#32]
**Is your feature request related to a problem? Please describe.**
if i use ctx.voice_channel the result is always None even the bot is connected to channel. Idk if its bug or feature

**Describe the solution you'd like**
I would like to use ctx.voice_channel 

**Describe alternatives you've considered**
Switching to different library which i dont want to bcs I like lavaplayer

**Additional context**
Discusion with discord py dev https://github.com/Rapptz/discord.py/issues/9026

**Comment by HazemMeqdad** [comment]
Try use `ctx..guild.voice_client`

**Comment by Karnatour** [comment]
Still gives None

**Comment by HazemMeqdad** [comment]
can you show me full code?

**Comment by Karnatour** [comment]
https://github.com/Karnatour/Votabot/blob/main/main.py
I host my own lavalink server could be problem here ?

**Comment by HazemMeqdad** [comment]
look to new version problem is solved.
