### ISSUE TITLE
Can't login in two different plugins

### ISSUE THREAD

**Issue by Tech-User42** [HazemMeqdad/lavaplay.py#38]
Hi, i need to connect from two different hikari plugins, but it only connect 1/2, is there a workaround ?

I need to access lavalink node in the second plugin to get the queue for example

**Comment by HazemMeqdad** [comment]
explain more.

**Comment by Tech-User42** [comment]
When i connect to lavaplayer with one hikari-lighbulb plugin i can't connect with another plugin, its like the connection to the server is limited to one connection

**Comment by HazemMeqdad** [comment]
No i think you can open 2 connection on once code, could tell me what you do.

**Comment by HazemMeqdad** [comment]
in a next version `1.0.11a`, you can open multi connection on different servers.

**Comment by HazemMeqdad** [comment]
What you mean by "plugins"

**Comment by HazemMeqdad** [comment]
You use different object, I suggest that Add Lavalink object on your bot class like:
# Commands
bot.lavalink = LavalinkClient(...)

# dashboard.py
await bot.lavalink.get_guild_node(TESTGUILD)

Also: You can update to a new version, now examples is not ready but you can read docs

**Comment by HazemMeqdad** [comment]
i understand you,
Before you start flask server you can make object of lavalink and add to bot object.
That way you can access on flask server and on bot

**Comment by HazemMeqdad** [comment]
dashboard.py
```pyhton
def run_server() -> None: # Lance le serveur Lavalink
    lavalink = lavaplyer.Lavalink()
    ...
    bot.lavalink = lavalink
    ...
```

music.py
```python
async def play_command(...):
    await plugin.bot.lavalink.play(...)
```
```

**Comment by Tech-User42** [comment]
I try but it give that error, i can't find how to add an attribute to the bot

![image](https://github.com/HazemMeqdad/lavaplay.py/assets/60147737/fc0e5177-0ca4-44d4-896b-5a155d28c0b4)

**Comment by HazemMeqdad** [comment]
I don't know how exactly this lib work but this is good way, try to find solution with your self.
this is outside my lib

**Comment by HazemMeqdad** [comment]
I will advice you and i l close this issue.
1- Try to find the solution with yourself, this problem depend on your code.
2- use a latest version of lavaplay package
