### ISSUE TITLE
KeyError identifier

### ISSUE THREAD

**Issue by Tech-User42** [HazemMeqdad/lavaplay.py#41]
Hello, i get randomly and error in lavaplay.py, its a KeyErrror which you can see in attachement, it happen totally randomly when starting a new track and i have to restart my bot in order to get it back working
![image](https://github.com/HazemMeqdad/lavaplay.py/assets/60147737/fab649ff-44e5-452f-a836-0ed274057310)

**Comment by HazemMeqdad** [comment]
I think sometimes the connection with lavalink server is not be successfully you will get randomly errors
