### ISSUE TITLE
Unable to play youtube video

### ISSUE THREAD

**Issue by Tech-User42** [HazemMeqdad/lavaplay.py#43]
Hi, recently i ran into an issue, i can't play YouTube video anymore this error occure on bot startup
![image](https://github.com/HazemMeqdad/lavaplay.py/assets/60147737/a6297bda-b5b6-4f72-a0d2-9f6bc30be65b)
And whennever i try to play a YouTube vid i get this error

![image](https://github.com/HazemMeqdad/lavaplay.py/assets/60147737/0ee56bde-12b3-45df-abe5-5d5b2b928c35)

**Comment by lavecat** [comment]
In french because he is french i guess ( En gros mais a jour ton lavaplay au dernière version et update ton lavalink a la v4 )
